"""Python consumer of the reviewed cross-language fixture corpus.

The Rust consumer lives in ``crates/fissionspec-core/tests`` and does not call
this module.  Expected values are fixture data, never generated by either
implementation during a parity run.
"""

from __future__ import annotations

import csv
import unittest
from pathlib import Path

from fissionspec.ledger import (
    FixedPageAllocator,
    LedgerEpoch,
    LedgerError,
    SpeculativeLedger,
)
from fissionspec.metrics import (
    batch_fallback_probability,
    expected_collateral_hit_stalls,
    head_of_line_amplification,
)
from fissionspec.policies import DispatchContext, FissionSpecPolicy
from fissionspec.profiles import HardwareProfile, LatencyCurve

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "cross_language"


def _rows(name: str) -> list[dict[str, str]]:
    lines = [
        line
        for line in (FIXTURES / name).read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    ]
    rows = list(csv.DictReader(lines, delimiter="\t"))
    if not rows or any(None in row or None in row.values() for row in rows):
        raise AssertionError(f"{name} is empty or malformed")
    cases = [row["case"] for row in rows]
    if len(cases) != len(set(cases)):
        raise AssertionError(f"{name} contains duplicate case names")
    return rows


def _probabilities(encoded: str) -> tuple[float, ...]:
    return tuple(float(value) for value in encoded.split(","))


def _points(encoded: str) -> tuple[tuple[int, float], ...]:
    if encoded == "-":
        return ()
    return tuple(
        (int(units), int(latency_ns) / 1_000_000.0)
        for units, latency_ns in (point.split(":") for point in encoded.split(";"))
    )


class AnalyticalMetricContractTests(unittest.TestCase):
    def test_reviewed_metric_fixtures(self) -> None:
        for row in _rows("metrics.tsv"):
            with self.subTest(case=row["case"]):
                misses = _probabilities(row["miss_probabilities"])
                hits = tuple(1.0 - miss for miss in misses)
                tolerance = float(row["tolerance"])
                fallback = batch_fallback_probability(hits)
                self.assertAlmostEqual(
                    1.0 - fallback,
                    float(row["survival_probability"]),
                    delta=tolerance,
                )
                self.assertAlmostEqual(
                    fallback,
                    float(row["batch_miss_probability"]),
                    delta=tolerance,
                )
                self.assertAlmostEqual(
                    head_of_line_amplification(hits),
                    float(row["hol_amplification"]),
                    delta=tolerance,
                )
                self.assertAlmostEqual(
                    expected_collateral_hit_stalls(hits),
                    float(row["expected_healthy_victims"]),
                    delta=tolerance,
                )


class LatencyContractTests(unittest.TestCase):
    def test_reviewed_latency_fixtures(self) -> None:
        for row in _rows("latency.tsv"):
            with self.subTest(case=row["case"]):
                curve = LatencyCurve(_points(row["points_ns"]))
                predicted_ns = curve.latency_ms(int(row["query_units"])) * 1_000_000.0
                self.assertAlmostEqual(predicted_ns, int(row["expected_ns"]), delta=1e-8)


class HorizonContractTests(unittest.TestCase):
    def test_reviewed_flattened_horizon_fixtures(self) -> None:
        for row in _rows("horizon2.tsv"):
            with self.subTest(case=row["case"]):
                current_count = int(row["current_count"])
                forecast_count = int(row["forecast_count"])
                current_deadline_ms = int(row["current_deadline_ns"]) / 1_000_000.0
                future_deadline_ms = (
                    None
                    if row["future_deadline_ns"] == "-"
                    else int(row["future_deadline_ns"]) / 1_000_000.0
                )
                forecast_at_ms = (
                    None
                    if row["forecast_at_ns"] == "-"
                    else int(row["forecast_at_ns"]) / 1_000_000.0
                )
                profile = HardwareProfile(
                    target_curve=LatencyCurve(_points(row["points_ns"])),
                    verifier_slot_ms=0.0,
                    name="cross-language-normalized-ns",
                )
                context = DispatchContext(
                    now_ms=0.0,
                    ready_count=current_count,
                    capacity=int(row["capacity"]),
                    oldest_ready_ms=0.0,
                    earliest_deadline_ms=current_deadline_ms,
                    row_slots=(1,) * current_count,
                    row_deadlines_ms=(current_deadline_ms,) * current_count,
                    profile=profile,
                    next_ready_time_ms=forecast_at_ms,
                    next_ready_count=forecast_count,
                    earliest_future_deadline_ms=future_deadline_ms,
                    future_row_slots=(1,) * forecast_count,
                    future_row_deadlines_ms=(
                        () if future_deadline_ms is None else (future_deadline_ms,) * forecast_count
                    ),
                )
                selected = FissionSpecPolicy(
                    max_wait_ms=int(row["max_wait_ns"]) / 1_000_000.0
                ).dispatch_at(context)
                actual = (
                    "wait"
                    if forecast_at_ms is not None and selected == forecast_at_ms
                    else "dispatch"
                )
                self.assertEqual(actual, row["expected_action"])


class TransactionContractTests(unittest.TestCase):
    def test_reviewed_version_fence_traces(self) -> None:
        for row in _rows("transactions.tsv"):
            with self.subTest(case=row["case"]):
                ledger = SpeculativeLedger(FixedPageAllocator(8, 1))
                ledger.register_request("fixture")
                current = ledger.begin("fixture", 0)
                results: list[str] = []
                for encoded in row["actions"].split(";"):
                    action, observed_version = encoded.split(":")
                    observed = LedgerEpoch(
                        current.request_id,
                        current.round_id,
                        int(observed_version),
                    )
                    try:
                        if action == "prepare":
                            ledger.stage_outcome(observed, "selected", 1)
                        elif action == "commit":
                            ledger.commit(observed, "selected", 1)
                        elif action == "abort":
                            ledger.abort(observed)
                        else:
                            raise AssertionError(f"unknown action {action!r}")
                    except LedgerError:
                        results.append("error")
                    else:
                        results.append("ok")
                    ledger.audit()
                self.assertEqual(";".join(results), row["expected_results"])
                view = ledger.request("fixture")
                snapshot = ledger.snapshot()
                if view.committed_blocks == 1 and view.active_epoch is None:
                    actual_state = "committed"
                elif current in snapshot.aborted_epochs and view.active_epoch is None:
                    actual_state = "aborted"
                else:
                    actual_state = "nonterminal"
                self.assertEqual(actual_state, row["expected_state"])


class MalformedBoundaryContractTests(unittest.TestCase):
    def test_every_malformed_fixture_is_rejected(self) -> None:
        handlers = {
            "metrics": self._reject_metric,
            "latency": self._reject_latency,
            "horizon2": self._reject_horizon,
        }
        for row in _rows("malformed.tsv"):
            with (
                self.subTest(case=row["case"]),
                self.assertRaises((TypeError, ValueError)),
            ):
                handlers[row["subsystem"]](row["payload"])

    @staticmethod
    def _reject_metric(payload: str) -> None:
        misses = _probabilities(payload)
        batch_fallback_probability(1.0 - miss for miss in misses)

    @staticmethod
    def _reject_latency(payload: str) -> None:
        LatencyCurve(_points(payload))

    @staticmethod
    def _reject_horizon(payload: str) -> None:
        field, encoded = payload.split("=")
        profile = HardwareProfile.linear()
        capacity = int(encoded) if field == "capacity" else 1
        service_units = int(encoded) if field == "service_units" else 1
        DispatchContext(
            now_ms=0.0,
            ready_count=1,
            capacity=capacity,
            oldest_ready_ms=0.0,
            earliest_deadline_ms=10.0,
            row_slots=(service_units,),
            row_deadlines_ms=(10.0,),
            profile=profile,
        )


if __name__ == "__main__":
    unittest.main()
